ALTER TABLE "Trip" ADD COLUMN "interests" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Trip" ADD COLUMN "preferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Trip" ADD COLUMN "notes" TEXT;
